@isTest(SeeAllData=true)
public class TargetAddViewExtTest {
    public static testMethod void test_importCSVFile(){ 
        /*
        ApexPages.StandardController controller = new ApexPages.StandardController(new Target__c());        
        TargetAddViewExt ctrl = new TargetAddViewExt(controller); 
        ctrl.csvFileBody = Blob.valueof('Target Name 1, 123456, 123456789012,aaa,,,,,,,\nTarget Name 1, 123456, 123456789012,aacount,brand,cat,,desc,10,oz,dep1');
        ctrl.importCSVFile();
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
		System.assertEquals(0, pageMessages.size());
        ctrl.csvFileBody = Blob.valueof('Target Name 1, 123456, 123456789012,aaa,,,,,,,\nTarget Name 1, 123456, 123456789012,,,,,,,,');
        ctrl.importCSVFile();
         pageMessages = ApexPages.getMessages();
		System.assertNotEquals(0, pageMessages.size());*/
	} 
}