public class ProjectImportJobsWrapper {
        @AuraEnabled
        public String PrjServiceName {get; set;}

        @AuraEnabled
        public String ServiceTitle {get; set;}

        @AuraEnabled
        public String PrjLocationName {get; set;}

        @AuraEnabled
        public String State {get; set;}

        @AuraEnabled
        public String City {get; set;}

        @AuraEnabled
        public String LocationNumber {get; set;}

        @AuraEnabled
        public String Banner {get; set;}

        @AuraEnabled
        public String JobName {get; set;}

        @AuraEnabled
        public String NumberOfWorkers {get; set;}

        @AuraEnabled
        public String JobStartDate {get; set;}

       @AuraEnabled
        public String JobStartTime {get; set;}
        
        @AuraEnabled
        public String PurchaseAmount {get; set;}
    }