@istest
public class TestDataSetExtTest {
	//public static testMethod void test_Method(){ 
 //       TestUtil.initBaseData();
 //       project__c p = new project__c();

        
 //       ApexPages.StandardController stdCtrl  = new ApexPages.StandardController(p);
 //       TestDataSetupExt ctrlExt = new TestDataSetupExt(stdCtrl); 
 //       system.assert(ctrlExt != null);
 //       ctrlExt.projCount=0;
 //       ctrlExt.projServcount=0;
 //       ctrlExt.projLocCount=0;
 //       ctrlExt.save();
		        
 //   } 
}